cache_path_public = 'algorithm/contrast/cache/'
train_generation_path_public = 'algorithm/contrast/train/'
test_generation_path_public = 'algorithm/contrast/test/'
ckpt_save_path_public = 'algorithm/contrast/model/'
result_path_public = 'algorithm/contrast/result_diff/'
log_path_public = 'algorithm/contrast/logs/'